<?php 
// *** ParseMX autogenerated script. Do not edit. Generated at February 14, 2013, 10:45 am
// *** SITE: localhost DONOR: bookup.me SECTION: product

ini_set('display_errors','On');$name =tag_text("h1");
$price =currency(tag_text(".price" ));
$main_image =tag_href(".image a");
$description =tag_html("#tab-description");
