<?php 
// *** ParseMX autogenerated script. Do not edit. Generated at April 8, 2014, 9:53 am
// *** SITE: rumus DONOR: brand-shop.net.ua SECTION: product

ini_set('display_errors','On');//AUTO START - сгенерировано автоматически;
$name =tag_text("h1");
find_manufacturer();
$price =tag_text(".b-product__price");
$description =tag_html(".b-user-content");
$main_image =tag_image(".b-product__image .b-centered-image__img");
$images =tags_image(".b-centered-image__img");
if (!$price and !empty($noprice)) $skip = true;
//AUTO END;

