<?php 
// *** ParseMX autogenerated script. Do not edit. Generated at April 8, 2014, 9:53 am
// *** SITE: rumus DONOR: brand-shop.net.ua SECTION: pass

ini_set('display_errors','On');/* Опции прописаные Мастером Инструкций */;
/**<h2 style='font-weight:normal'>Настройки парсинга</h2>**/;
global $description_images, $site_language, $noprice, $update_price, $update_name, $update_description, $update_images, $update_attributes, $update_options;
$description_images = false;
$site_language = "";
$noprice = false;
$update_price = true;
$update_description = false;
$update_images = false;
$update_attributes = true;
$update_options = true;
