<?php 
// *** ParseMX autogenerated script. Do not edit. Generated at April 8, 2014, 9:53 am
// *** SITE: rumus DONOR: brand-shop.net.ua SECTION: list

ini_set('display_errors','On');//AUTO LIST START - сгенерировано автоматически;
$products =tags_href(".b-product-line__product-name-link");
$nextpage =inside( "f=\"", "\"",inside("\"/g2369951-novinki-nashego-magazina/page_12?product_items_per_page=48\"", "&" ));
$nextpage = "http://brand-shop.net.ua$nextpage";


InsertCategory();
