<?php 
// *** ParseMX autogenerated script. Do not edit. Generated at March 4, 2014, 1:55 pm
// *** SITE: rumus DONOR: ebay.com SECTION: list

ini_set('display_errors','On');//AUTO LIST START - сгенерировано автоматически;
$products =tags_href(".vip");


InsertCategory();
