<?php 
// *** ParseMX autogenerated script. Do not edit. Generated at March 4, 2014, 1:55 pm
// *** SITE: rumus DONOR: ebay.com SECTION: product

ini_set('display_errors','On');//AUTO START - сгенерировано автоматически;
$name =tag_text("h1");
find_manufacturer();
$description =inside("e\" src=\"", "\"");
$main_image =inside("e\" src=\"", "\"");
$images =insides("g src=\"", "\"");
$price =inside("$", " ");
if (!$price and !empty($noprice)) $skip = true;
//AUTO END;

