<?php 
// *** ParseMX autogenerated script. Do not edit. Generated at March 11, 2014, 12:27 pm
// *** SITE: rumus.by DONOR: moonar.ebay.com SECTION: list

ini_set('display_errors','On');//AUTO LIST START - сгенерировано автоматически;
$nextpage =tag_href("//*[contains(concat( ' ', @class, ' ' ), concat( ' ', 'pg', ' ' )) and (((count(preceding-sibling::*) + 1) = 7) and parent::*)]");
$products =tags_href(".vip");


InsertCategory();
