<?php 
// *** ParseMX autogenerated script. Do not edit. Generated at March 11, 2014, 12:27 pm
// *** SITE: rumus.by DONOR: moonar.ebay.com SECTION: product

ini_set('display_errors','On');//AUTO START - сгенерировано автоматически;
$name =tag_text("h1");
find_manufacturer();
$description =inside("e\" src=\"", "\"");
$main_image =inside("e\" src=\"", "\"");
$images =insides("g src=\"", "\"");
$price =inside("$", " ");
if (!$price and !empty($noprice)) $skip = true;
//AUTO END;

