<?php 
// *** ParseMX autogenerated script. Do not edit. Generated at March 7, 2014, 10:09 am
// *** SITE: rumus.by DONOR: stores.ebay.com SECTION: list

ini_set('display_errors','On');//AUTO LIST START - сгенерировано автоматически;
$products =tags_href("a");




InsertCategory();
