<?php 
// *** ParseMX autogenerated script. Do not edit. Generated at March 7, 2014, 10:09 am
// *** SITE: rumus.by DONOR: stores.ebay.com SECTION: product

ini_set('display_errors','On');//AUTO START - сгенерировано автоматически;
$name =tag_text("h1");
find_manufacturer();
$price =inside("$", " ");
$main_image =inside("e\" src=\"", "\"");
$images =tags_image("img");
if (!$price and !empty($noprice)) $skip = true;
//AUTO END;

